# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aqi',
            fields=[
                ('aqi_id', models.AutoField(primary_key=True, serialize=False)),
                ('aqi_area', models.CharField(max_length=10)),
                ('aqi_index', models.IntegerField()),
                ('aqi_pubdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AQI',
            },
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('cap_id', models.AutoField(primary_key=True, serialize=False)),
                ('cap_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'capacity',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_title', models.CharField(max_length=50)),
                ('com_con', models.TextField(max_length=500)),
                ('com_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('ins_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ins_type', models.CharField(max_length=10)),
                ('ins_name', models.CharField(max_length=51)),
                ('agent', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='backend.City')),
            ],
            options={
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='Institutions_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bed', models.CharField(max_length=20)),
                ('Cap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='backend.Capacity')),
                ('Ins_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='backend.Institution')),
            ],
            options={
                'db_table': 'institution_unit',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='fav_intitu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_unit', to='backend.Institutions_Unit'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='mem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_Unitcomment', to='backend.Institutions_Unit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aqi',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityaqi', to='backend.City'),
        ),
        migrations.AlterUniqueTogether(
            name='institutions_unit',
            unique_together=set([('Ins_id', 'Cap_id')]),
        ),
    ]
